name: Build and Release

on:
  release:
    types: [created, edited]


# Définit les permissions nécessaires pour l'action de publication
permissions:
  contents: read # Autorise à lire le contenu du dépôt
  # id-token: write # Décommentez cette ligne si vous utilisez l'authentification OIDC "Trusted Publishing" (plus avancé)

jobs:
  # Tâche unique pour construire et publier
  deploy:
    runs-on: ubuntu-latest # Utilise une machine virtuelle Ubuntu

    steps:
      # 1. Récupérer le code du dépôt
      - uses: actions/checkout@v4
        # Télécharge le code correspondant au tag poussé

      # 2. Configurer l'environnement Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Utilise la dernière version stable de Python 3.x
          # Vous pouvez spécifier une version exacte si nécessaire, ex: '3.10'

      # 3. Installer les dépendances de build
      - name: Install build dependencies
        run: python -m pip install --upgrade build
        # Installe/met à jour le package 'build' recommandé par PyPA

      # 4. Construire les distributions source et wheel
      - name: Build package
        run: python -m build
        # Exécute le processus de build standard, qui lit votre pyproject.toml
        # Crée les fichiers .tar.gz et .whl dans le dossier 'dist/'

      # 5. Publier la distribution sur PyPI
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # Utilise un jeton d'API stocké dans les secrets GitHub
          # IMPORTANT: Créez un secret nommé 'PYPI_API_TOKEN' dans les paramètres de votre dépôt GitHub
          # (Settings > Secrets and variables > Actions > New repository secret)
          # et collez-y votre jeton d'API PyPI.
          password: ${{ secrets.PYPI_API_TOKEN }}
          # Décommentez la ligne suivante pour publier sur TestPyPI à la place
          # repository_url: https://test.pypi.org/legacy/

      # Optionnel : Publier sur TestPyPI (si vous voulez tester avant)
      # - name: Publish package to TestPyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     # IMPORTANT: Utilisez un jeton d'API généré sur test.pypi.org
      #     # et stocké dans un secret différent (ex: TEST_PYPI_API_TOKEN)
      #     password: ${{ secrets.TEST_PYPI_API_TOKEN }}
      #     repository_url: https://test.pypi.org/legacy/
